version: '3.7'

x-environment:
    &default-environment
    POSTGRES_USER: vscode
    POSTGRES_PASSWORD: notsecure
    POSTGRES_DB: tutorial
services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/server.dockerfile
        environment:
            <<: *default-environment
            PORT: 3000
        ports:
            - 3000:3000
        volumes:
            - ..:/workspace        
        command: sleep infinity
    client:
        build:
            context: ..
            dockerfile: .devcontainer/server.dockerfile
        environment:
            <<: *default-environment
            PORT: 8100
        ports:
            - 8100:8100
        volumes:
            - ..:/workspace        
        command: sleep infinity
    db:
        image: "postgres:12"
        restart: always
        environment: *default-environment
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        restart: always
        environment: *default-environment
        ports:
            - 8080:8080
volumes:
    pgdata:
